@startuml

start

:melakukan request API;

partition library HTTP client {
    if (apakah sudah\nmemiliki token?) then (tidak)
        :lakukan login untuk
        mendapatkan token;
    else (ya)
    endif

    if (apakah token\nsudah kedaluarsa\natau sebentar lagi\nakan kedaluarsa?) then (ya)
        :lakukan login ulang untuk
        mendapatkan token;
    else (tidak)
    endif

    :lakukan request
    menggunakan token;

    if (apakah responsenya 401?) then (ya)
        :lakukan login ulang untuk
        mendapatkan token;
        :ulangi request dengan
        token yang baru;
    else (tidak)
    endif

    :return responsenya;
}

:mendapatkan response dari API;

end

@enduml
